'use strict';

/**
 * @fileoverview Output formatters — JSON, CSV, TSV, HTML, Excel, SQL, TXT.
 * @module services/formatters/index
 */

const path = require('path');
const fs = require('fs');
const config = require('../../config');
const { ensureDir, writeFile } = require('../../utils/fsUtil');
const { createLogger } = require('../monitor/logger');

const log = createLogger('formatters');

/**
 * Format items to JSON string.
 * @param {Object[]} items
 * @param {Object} [meta]
 * @returns {string}
 */
function toJson(items, meta = {}) {
  return JSON.stringify({ meta, data: items, count: items.length }, null, 2);
}

/**
 * Format items to CSV string.
 * @param {Object[]} items
 * @returns {string}
 */
function toCsv(items) {
  if (items.length === 0) return '';
  const headers = Object.keys(items[0]);
  const escape = (val) => {
    const str = String(val == null ? '' : val);
    return str.includes(',') || str.includes('"') || str.includes('\n')
      ? `"${str.replace(/"/g, '""')}"`
      : str;
  };
  const rows = items.map(item => headers.map(h => escape(item[h])).join(','));
  return [headers.join(','), ...rows].join('\n');
}

/**
 * Format items to TSV string.
 * @param {Object[]} items
 * @returns {string}
 */
function toTsv(items) {
  if (items.length === 0) return '';
  const headers = Object.keys(items[0]);
  const escape = (val) => String(val == null ? '' : val).replace(/\t/g, ' ').replace(/\n/g, ' ');
  const rows = items.map(item => headers.map(h => escape(item[h])).join('\t'));
  return [headers.join('\t'), ...rows].join('\n');
}

/**
 * Format items to HTML table string.
 * @param {Object[]} items
 * @param {Object} [meta]
 * @returns {string}
 */
function toHtml(items, meta = {}) {
  if (items.length === 0) return '<p>No data</p>';
  const headers = Object.keys(items[0]);
  const esc = (s) => String(s == null ? '' : s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

  let html = `<!DOCTYPE html><html><head><meta charset="utf-8">
<title>${esc(meta.keyword || 'Results')}</title>
<style>body{font-family:system-ui,sans-serif;margin:2rem;background:#1a1a2e;color:#e0e0e0}
table{border-collapse:collapse;width:100%;margin-top:1rem}
th{background:#16213e;color:#0f3460;padding:10px;text-align:left;color:#e94560}
td{padding:8px;border-bottom:1px solid #333}
tr:hover{background:#16213e}
a{color:#0f3460;text-decoration:none}
h1{color:#e94560}
.meta{color:#888;font-size:0.9em}</style></head><body>
<h1>📊 ${esc(meta.keyword || 'Scrape Results')}</h1>
<p class="meta">Provider: ${esc(meta.providerUsed || '-')} | Total: ${items.length} items</p>
<table><thead><tr>${headers.map(h => `<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>`;

  for (const item of items) {
    html += '<tr>';
    for (const h of headers) {
      let val = item[h];
      if (typeof val === 'string' && val.startsWith('http')) {
        html += `<td><a href="${esc(val)}" target="_blank">${esc(val.slice(0, 60))}...</a></td>`;
      } else {
        html += `<td>${esc(val)}</td>`;
      }
    }
    html += '</tr>';
  }

  html += '</tbody></table></body></html>';
  return html;
}

/**
 * Format items to SQL INSERT statements.
 * @param {Object[]} items
 * @param {string} [tableName='scrape_results']
 * @returns {string}
 */
function toSql(items, tableName = 'scrape_results') {
  if (items.length === 0) return '';
  const headers = Object.keys(items[0]);
  const esc = (val) => {
    if (val == null) return 'NULL';
    if (typeof val === 'number') return String(val);
    if (typeof val === 'boolean') return val ? '1' : '0';
    return `'${String(val).replace(/'/g, "''")}'`;
  };

  let sql = `-- Generated by ${config.botName}\n`;
  sql += `-- ${new Date().toISOString()}\n\n`;
  sql += `CREATE TABLE IF NOT EXISTS ${tableName} (\n`;
  sql += headers.map(h => `  ${h.replace(/[^a-zA-Z0-9_]/g, '_')} TEXT`).join(',\n');
  sql += '\n);\n\n';

  for (const item of items) {
    const cols = headers.join(', ');
    const vals = headers.map(h => esc(item[h])).join(', ');
    sql += `INSERT INTO ${tableName} (${cols}) VALUES (${vals});\n`;
  }

  return sql;
}

/**
 * Format items to plain text.
 * @param {Object[]} items
 * @param {Object} [meta]
 * @returns {string}
 */
function toTxt(items, meta = {}) {
  let txt = `=== ${meta.keyword || 'Results'} ===\n`;
  txt += `Provider: ${meta.providerUsed || '-'} | Total: ${items.length}\n`;
  txt += '='.repeat(50) + '\n\n';

  items.forEach((item, i) => {
    txt += `[${i + 1}] ${item.title || 'Untitled'}\n`;
    if (item.url) txt += `    URL: ${item.url}\n`;
    if (item.description) txt += `    ${item.description.slice(0, 200)}\n`;
    if (item.authors) txt += `    Authors: ${item.authors}\n`;
    if (item.year) txt += `    Year: ${item.year}\n`;
    txt += '\n';
  });

  return txt;
}

/**
 * Format items to Excel file and return filepath.
 * @param {Object[]} items
 * @param {Object} [meta]
 * @param {string} [outputDir]
 * @returns {Promise<string>} File path
 */
async function toExcel(items, meta = {}, outputDir) {
  const ExcelJS = require('exceljs');
  const dir = outputDir || config.dirs.outputs;
  await ensureDir(dir);

  const workbook = new ExcelJS.Workbook();
  workbook.creator = config.botName;
  workbook.created = new Date();

  const sheet = workbook.addWorksheet('Results');

  if (items.length === 0) {
    sheet.addRow(['No data']);
  } else {
    const headers = Object.keys(items[0]);
    const headerRow = sheet.addRow(headers);

    // Style header
    headerRow.eachCell(cell => {
      cell.font = { bold: true, color: { argb: 'FFFFFF' } };
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: '0F3460' } };
      cell.alignment = { horizontal: 'center' };
    });

    // Data rows
    for (const item of items) {
      sheet.addRow(headers.map(h => item[h] != null ? String(item[h]) : ''));
    }

    // Auto-width columns
    sheet.columns.forEach(col => {
      let maxLen = 10;
      col.eachCell({ includeEmpty: true }, cell => {
        const len = cell.value ? String(cell.value).length : 0;
        if (len > maxLen) maxLen = Math.min(len, 50);
      });
      col.width = maxLen + 2;
    });
  }

  const keyword = (meta.keyword || 'results').replace(/[^a-zA-Z0-9]/g, '_').slice(0, 30);
  const filename = `${keyword}_${Date.now()}.xlsx`;
  const filepath = path.join(dir, filename);
  await workbook.xlsx.writeFile(filepath);

  log.info(`Excel file created: ${filename}`);
  return filepath;
}

/**
 * Format and save items to file based on format type.
 * @param {Object[]} items
 * @param {string} format - json|csv|tsv|html|excel|sql|txt
 * @param {Object} [meta]
 * @returns {Promise<{ filepath: string, content: string|null }>}
 */
async function formatAndSave(items, format, meta = {}) {
  const dir = config.dirs.outputs;
  await ensureDir(dir);
  const keyword = (meta.keyword || 'results').replace(/[^a-zA-Z0-9]/g, '_').slice(0, 30);
  const timestamp = Date.now();

  let content, ext;

  switch (format) {
    case 'csv':
      content = toCsv(items);
      ext = 'csv';
      break;
    case 'tsv':
      content = toTsv(items);
      ext = 'tsv';
      break;
    case 'html':
      content = toHtml(items, meta);
      ext = 'html';
      break;
    case 'sql':
      content = toSql(items);
      ext = 'sql';
      break;
    case 'txt':
      content = toTxt(items, meta);
      ext = 'txt';
      break;
    case 'excel':
      return { filepath: await toExcel(items, meta), content: null };
    case 'json':
    default:
      content = toJson(items, meta);
      ext = 'json';
      break;
  }

  const filepath = path.join(dir, `${keyword}_${timestamp}.${ext}`);
  await writeFile(filepath, content);
  log.info(`Formatted output saved: ${path.basename(filepath)}`);

  return { filepath, content };
}

module.exports = { toJson, toCsv, toTsv, toHtml, toSql, toTxt, toExcel, formatAndSave };
